# Setup
title: Raz Peleg
tagline: Game Designer
description: "My projects portfolio showcasing my Game Design skills."
baseurl: "/game-design-portfolio"
# paginate: 5
permalink: pretty

# About/contact
author:
  name: Raz Peleg
  email: r@zpeleg.com

# Plugins
#plugins:
#  - jekyll-paginate

# Custom vars
version: 0.0.1
google_analytics_id: #UA-XXXX-Y
