# Setup
title: Raz Peleg
tagline: Game Designer
description: "My projects portfolio showcasing my Game Design skills."
baseurl: "/game-design-portfolio"
url: "https://subugdubug.github.io"
# paginate: 5
permalink: pretty
repository: subugdubug/game-design-portfolio

# About/contact
author:
  name: Raz Peleg
  email: r@zpeleg.com

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Custom vars
version: 0.0.1
google_analytics_id: #UA-XXXX-Y
